"""empty message

Revision ID: 1b4869c8c0c1
Revises: 
Create Date: 2023-04-30 14:19:36.623165

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b4869c8c0c1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expence",
        sa.Column("expence", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("expence_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("expence", name=op.f("pk__expence")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expence")
    # ### end Alembic commands ###
